### PR TITLE
Fix routes stat tests

### PR DESCRIPTION
**Pull request by KevinDyer**

### CODE REVIEW

**Comment by jeffdyer** [comment]
'make test' is throwing an error
`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`
Thoughts?

**Comment by KevinDyer** [comment]
I'm seeing that too on the master branch. This change should fix that.
Cleaning my environment and remaking to ensure this actual fixes those tests

**Comment by jeffdyer** [comment]
Probably a collision with a change I made.

**Comment by KevinDyer** [comment]
Are the tests still not passing for you?

**Pull request merged**
